### PR TITLE
Aligned Code of conduct page and Privacy policy Page

### PR DESCRIPTION
**Pull request by Subaharish**

### CODE REVIEW

**Comment by newb-dev-1008** [comment]
Hold on @aravindvnair99

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Conflicts with #7 

@newb-dev-1008 how many are working on the same thing?

**Comment by newb-dev-1008** [comment]
Yeah @aravindvnair99 these are the same changes in #7, that PR actually has the same changes if not more. So you can merge #7

**Comment by aravindvnair99** [comment]
> Yeah @aravindvnair99 these are the same changes in #7, that PR actually has the same changes if not more. So you can merge #7

Alright @newb-dev-1008, closing this.

**Pull request closed without merging**
